### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by Akayreddine** [CUBEb4g1/Projet-CUBE-Web#11]
@PhoenixiaProds
- [ ] Controller
- [ ] View

**Comment by PhoenixiaProds** [comment]
.blade files created with some content : 

- about.blade
- contact.blade
- footer.blade
- service.blade
- testimonial.blade

Still need some sass to make it beautifullllll

**Comment by PhoenixiaProds** [comment]
Images still missing but colors mostly corrected.

Some content added.

**Comment by PhoenixiaProds** [comment]
Finally added navbar (Logo misisng on it for now and Burger menu for low res screens)

Lots of images and icons.

Small improvement with Login / Register links.

**Comment by PhoenixiaProds** [comment]
Sticky navbar now implemented

Navbar and footer also look like twins with similar display methods.

Minor visual improvements were made.

**Comment by PhoenixiaProds** [comment]
New improvements : 

- Better readability over home banner
- Parallax effect on service section
- Fresh background on team section with custom avatars for crew members

**Comment by PhoenixiaProds** [comment]
Back to Top button implemented

Font Awesome icons not showing up when included. Investigation needed

**Comment by PhoenixiaProds** [comment]
Font awesome icon correctly displayed now \o/
