### ISSUE TITLE
Créer Relation

### ISSUE THREAD

**Issue by Akayreddine** [CUBEb4g1/Projet-CUBE-Web#14]
@toolib-kent
- [ ] Migration
- [ ] Model
- [ ] Controller

**Comment by toolib-kent** [comment]
![image](https://user-images.githubusercontent.com/69673350/102986204-bd245400-4510-11eb-9c36-8597d2b24340.png)

![image](https://user-images.githubusercontent.com/69673350/102986155-a847c080-4510-11eb-9fc9-911e9c593978.png)
