### ISSUE TITLE
[HELP] Font Awesome icons not showing up

### ISSUE THREAD

**Issue by PhoenixiaProds** [CUBEb4g1/Projet-CUBE-Web#30]
Suite a l'implementation du bouton de retour en haut de page, les icones font awesome n'apparaissent pas sur la page web.

[Fichier app.css ici](https://github.com/CUBEb4g1/Projet-CUBE-Web/blob/feat/homepage/resources/assets/sass/front/app.scss)

`.progress-wrap::before {
    position:                       absolute;
    content:                        "\f102";
    ...
}`

Merci pour le support sur ce point :)

**Comment by toolib-kent** [comment]
Where did you import the font-awesome library in the head, or somewhere else ?
Can't see it in the HTML or in the CSS, maybe I missed something...

![image](https://user-images.githubusercontent.com/69673350/103226736-120b0480-492d-11eb-9237-e4ddd1070d9f.png)

**Comment by PhoenixiaProds** [comment]
Thanks for reply.

I failed hard, missed to call font into scss file  :D 

Now clear : 

`&:before {
        font-family:                "Font Awesome 5 Pro", sans-serif;`
