### ISSUE TITLE
[BUG] Problems with CSS

### ISSUE THREAD

**Issue by smachball21** [CUBEb4g1/Projet-CUBE-Web#65]
Login & Register FORM :

![unknown](https://user-images.githubusercontent.com/69909407/104728112-b61aeb00-5736-11eb-9327-40a5fc39c896.png)
![unknown2](https://user-images.githubusercontent.com/69909407/104728115-b6b38180-5736-11eb-9fb5-6a5b0aba0868.png)

Bloc de recherche : 
Changer fontweight
![image](https://user-images.githubusercontent.com/69909407/104729333-8ff64a80-5738-11eb-8fbc-136fdc6cfc9f.png)

Card of the resources:
![image](https://user-images.githubusercontent.com/69909407/104729415-af8d7300-5738-11eb-9dbf-beb7d5ae8e19.png)

**Comment by PhoenixiaProds** [comment]
Etat des fixs

- [ ] Login and Register forms
- [ ] Bloc de recherche : Changer fontweight
- [ ] Card of the resoources
