### ISSUE TITLE
Architecture reseau 

### ISSUE THREAD

**Issue by toolib-kent** [CUBEb4g1/Projet-CUBE-Web#68]
- [x] Proposer une architecture cohérente
- [x] Diagramme réseau
- [x] Proposer une solution de déploiement
- [x] Chiffrer le cout de la solution

**Comment by toolib-kent** [comment]
Projet de déploiement créé sous Gitlab

Github ne permet pas toute les options de déploiement et de pipeline dans sa version gratuite. J'ai donc lié les répo Github et Gitlab.

https://gitlab.com/cube-dev

**Comment by PhoenixiaProds** [comment]
Issue closed, part included into final doc
