### ISSUE TITLE
Create ResourceType

### ISSUE THREAD

**Issue by toolib-kent** [CUBEb4g1/Projet-CUBE-Web#8]
@toolib-kent
- [ ] Migration
- [ ] Model
- [ ] Controller

**Comment by toolib-kent** [comment]
#8

**Comment by toolib-kent** [comment]
Si j'ai bien compris pour créer model, migration et controller :

```
php artisan make:model -mc ResourceType

-m, --migration 
-c, --controller 
-r, --resource
```

@Kayreddine @Akayreddine, je m'y prend un peu tard, mais si tu as plus de précisions à me donner

**Comment by Akayreddine** [comment]
Ouais il te faut le Model, le Controller et la migration, pas de -r on en a pas besoin dans ce cas là.
Une fois que tu as ça, tu pourrais remplir ta migration et finir de param ton Model (le $fillable et les relations si besoin).

Quand tu as fait ta migration oublie pas de faire un migrate ! (tu peux faire un migrate:fresh pour refaire ta DB intégralement) @toolib-kent .

**Comment by toolib-kent** [comment]
Ok c'est noté, merci.
Je m'imaginais un truc super chaud à faire, mais ca devrai aller !

**Comment by toolib-kent** [comment]
![image](https://user-images.githubusercontent.com/69673350/102986077-7e8e9980-4510-11eb-98b3-6cefd1fc2c2a.png)

![image](https://user-images.githubusercontent.com/69673350/102986099-8f3f0f80-4510-11eb-9c07-057b7d647abd.png)
